apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: gitea
        env:
          - name: "GITEA_CUSTOM"
            value: "/etc/gitea/custom"
          - name: "PGPASSWORD"
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
        volumeMounts:
          - mountPath: "/etc/gitea/custom/conf"
            name: config-volume
