namespace: gitea

resources:
  - volumes.yaml
  - gitea.yml

patches:
  - deployment-patch.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: gitea
  path: volmount-patch.yaml
